description = "Define a estratégia de deploy, pipeline, RTO/RPO e os requisitos de qualidade como SLOs e métricas."

prompt = """
---
description: Define a estratégia de deploy, pipeline, RTO/RPO e os requisitos de qualidade como SLOs e métricas.
---

# Build
<!-- markdownlint-disable MD012 MD029 MD031 MD032 MD036 -->

## User Input

```text
{{args}}
```

Você **DEVE** considerar o briefing do time antes de prosseguir (quando fornecido).

## Goal

---
description: Define a estratégia de deploy, pipeline, RTO/RPO e os requisitos de qualidade como SLOs e métricas.
---

## Operating Constraints

_Nenhuma restrição específica definida._

## Execution Steps

## Context
"""
