description = "Cria um novo Cenário BDD (SCN) para uma funcionalidade, ligando-o ao Ator e ao Container responsáveis."

prompt = """
---
description: Cria um novo Cenário BDD (SCN) para uma funcionalidade, ligando-o ao Ator e ao Container responsáveis.
---

# Feature
<!-- markdownlint-disable MD012 MD029 MD031 MD032 MD036 -->

## User Input

```text
{{args}}
```

Você **DEVE** considerar o briefing do time antes de prosseguir (quando fornecido).

## Goal

---
description: Cria um novo Cenário BDD (SCN) para uma funcionalidade, ligando-o ao Ator e ao Container responsáveis.
---

## Operating Constraints

_Nenhuma restrição específica definida._

## Execution Steps

## Context
"""
