description = "Cria os artefatos do design inicial: Container, Componente e Cenário BDD principal."

prompt = """
---
description: Cria os artefatos do design inicial: Container, Componente e Cenário BDD principal.
---

# Plan
<!-- markdownlint-disable MD012 MD029 MD031 MD032 MD036 -->

## User Input

```text
{{args}}
```

Você **DEVE** considerar o briefing do time antes de prosseguir (quando fornecido).

## Goal

---
description: Cria os artefatos do design inicial: Container, Componente e Cenário BDD principal.
---

## Operating Constraints

_Nenhuma restrição específica definida._

## Execution Steps

## Context
"""
