description = "Cria ou atualiza uma regra de código (pattern) com critérios objetivos e mensuráveis."

prompt = """
---
description: Cria ou atualiza uma regra de código (pattern) com critérios objetivos e mensuráveis.
---

# Rule
<!-- markdownlint-disable MD012 MD029 MD031 MD032 MD036 -->

## User Input

```text
{{args}}
```

Você **DEVE** considerar o briefing do time antes de prosseguir (quando fornecido).

## Goal

---
description: Cria ou atualiza uma regra de código (pattern) com critérios objetivos e mensuráveis.
---

## Operating Constraints

_Nenhuma restrição específica definida._

## Execution Steps

## Context
"""
