description = "Define a stack tecnológica, restrições e cria o ADR-001 para justificar a escolha."

prompt = """
---
description: Define a stack tecnológica, restrições e cria o ADR-001 para justificar a escolha.
---

# Stack
<!-- markdownlint-disable MD012 MD029 MD031 MD032 MD036 -->

## User Input

```text
{{args}}
```

Você **DEVE** considerar o briefing do time antes de prosseguir (quando fornecido).

## Goal

---
description: Define a stack tecnológica, restrições e cria o ADR-001 para justificar a escolha.
---

## Operating Constraints

_Nenhuma restrição específica definida._

## Execution Steps

## Context
"""
