description = "Define a visão, objetivos, escopo e termos iniciais do projeto."

prompt = """
---
description: Define a visão, objetivos, escopo e termos iniciais do projeto.
---

# Vision
<!-- markdownlint-disable MD012 MD029 MD031 MD032 MD036 -->

## User Input

```text
{{args}}
```

Você **DEVE** considerar o briefing do time antes de prosseguir (quando fornecido).

## Goal

---
description: Define a visão, objetivos, escopo e termos iniciais do projeto.
---

## Operating Constraints

_Nenhuma restrição específica definida._

## Execution Steps

## Context
"""
